# Do this for system configs

from langchain_google_genai import ChatGoogleGenerativeAI
import subprocess

systemPrompt = '''
    You need to generate commands according to the users requirement for a debian based OS. Follow the below steps line by line
    Step 1: Understand what the user wants to achieve
    Step 2: Remember that the commands generated by you will be written to a shell file directly. Generate the commands ONLY. Do not enclose the commands in any formatting like ```bash
    Step 2: According to the specified operating system, generate the commands.

    Example 1:

    User: Update my stytem
    AI: "
        #!/bin/bash
        sudo apt update
    "
'''

llm = ChatGoogleGenerativeAI(
    model="gemini-2.0-flash",
    temperature=0
)

while(True):

    task = input("Task: ")
    response = llm.invoke(f"{systemPrompt}. The requirement is: {task}")
    with open('gpt_generated_commands.sh', 'w') as f:
        f.write(response.content)
        subprocess.run(["chmod", "+x", "gpt_generated_commands.sh"], capture_output=True)
    run_file = input("Execute file[ny]: ")
    if(run_file == "y"):
        subprocess.run(["./gpt_generated_commands.sh"], capture_output=True)
        


